export enum ExpectedYield {
  YIELD_FIRST = 'YIELD_FIRST',
  BALANCED_YIELD = 'BALANCED_YIELD',
  OUTSTRIPPING_INFLATION = 'OUTSTRIPPING_INFLATION',
  OUTSTRIPPING_INTEREST = 'OUTSTRIPPING_INTEREST'
}
